name: Automated Commit

on:
  push:
    branches: [master] # Ensures the workflow triggers on pushes to master

  schedule:
    - cron: '0 0 * * *' # Executes every day

  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write # Grants permissions to write to the repo

jobs:
  update_commit:
    runs-on: ubuntu-latest # Specifies the runner

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{github.ref}}"

      - name: Generate Random Delay
        run: |
          RANDOM_HOURS=$(( RANDOM % (24 - 12 + 1) + 12 ))
          echo "RANDOM_HOURS=$RANDOM_HOURS" >> $GITHUB_ENV

      - name: Wait for Random Delay
        run: |
          sleep $(( ${RANDOM_HOURS} * 3600 ))

      - name: Checkout Code
        uses: actions/checkout@v3 # Latest version for optimized performance
        with:
          persist-credentials: true # Ensures credentials are available for subsequent steps
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "mail"
          git config user.name "mail"

      - name: Prepare Commit
        run: |
          commit_messages=("Update:" "Refresh:" "Renew:" "Revise:" "Amend:" "Adjust:" "Change:" "Modify:" "Transform:" "Revamp:")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
          
          git add TIMESTAMP.txt
          git commit -m "$random_msg $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
